# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
- task: NodeTool@0
  inputs:
   versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

- script: npm install --save-dev sass
  displayName: 'npm install sass'

- script: sass scss:assets/css
  displayName: 'npm compile scss'

- script: npm install --save-dev typescript
  displayName: 'npm install typescript'

- script: npm install --save-dev terser
  displayName: 'npm install terser'

# TSC should pick the tsconfig options up
- script: tsc  && terser assets/js/custom.js -o assets/js/custom.min.js
  displayName: 'npm compile typescript'

- task: ArchiveFiles@2
  inputs:
   rootFolderOrFile: '$(Build.SourcesDirectory)'
   archiveType: 'zip'
   archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
   replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
